name: iit_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_value: ^6.7.0
  chopper: ^2.4.2
  clippy_flutter: ^1.1.1
  connectivity: ^2.0.2

  cupertino_icons: ^0.1.2
  fab_circular_menu:
  firebase_auth: ^0.18.4+1

  firebase_core: ^0.5.3
  firebase_dynamic_links: ^0.6.3
  firebase_messaging: "^8.0.0-dev.11"
  firebase_storage: ^5.2.0
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2
  font_awesome_flutter:
  google_fonts:
  google_maps_flutter:

  # esys_flutter_share: ^1.0.2
  google_sign_in: ^4.0.7
  http: ^0.12.1
  image_picker: ^0.6.7+14
  intl:
  package_info: ^0.4.3+2
  path_provider: ^1.5.1
  photo_view: ^0.10.3
  provider: ^3.0.0+1
  share_plus:
  shared_preferences: ^0.5.6+3
  skeleton_text: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  sqflite: ^1.2.0
  url_launcher: ^5.1.6
  file: ^6.1.4

  # web
  universal_io: ^1.0.2
  colorful_safe_area: ^0.3.0
  fluttertoast: ^8.1.2

dev_dependencies:
  # No version number means the latest version
  build_runner:
  built_value_generator: ^6.7.0
  chopper_generator: ^2.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/academics/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
